---
- name: Install PHPMyAdmin
  yum:
    name: phpmyadmin
    state: present

- name: Create symlink for PHPMyAdmin
  file:
    src: '/usr/share/phpMyAdmin'
    dest: '/usr/share/phpmyadmin'
    state: link

- name: Import phpmyadmin data
  mysql_db:
    login_host: '{{ phpmyadmin_host }}'
    login_user: '{{ phpmyadmin_user }}'
    login_password: '{{ phpmyadmin_pass }}'
    name: 'phpmyadmin'
    state: import
    target: '/usr/share/phpMyAdmin/sql/create_tables.sql'

- name: Include RedHat Vars
  include_vars: RedHat.yml
