---
- name: Configure Repository
  apt_repository:
    repo: 'deb http://apt.newrelic.com/debian/ newrelic non-free'
    state: present
    update_cache: yes

- name: Add GPG Key
  apt_key:
    url: 'https://download.newrelic.com/548C16BF.gpg'
    state: present

- name: Install NewRelic Agent
  apt:
    name: newrelic-sysmond
    state: present
