---
- name: Start MySQL
  service:
    name: mysql
    state: started

- name: Ensure /etc/mysql/ exists
  file:
    path: '/etc/mysql'
    state: directory

- name: Ensure /etc/mysql/conf.d/ exists
  file:
    path: '/etc/mysql/conf.d'
    state: directory

- name: Check if .configured is set
  stat:
    path: '/etc/mysql/.configured'
  register: galera_configured

- name: Set Root Password
  mysql_user:
    name: root
    password: '{{ galera_root_password }}'
  when: not galera_configured.stat.exists

- name: Configure .my.cnf
  template:
    src: 'Common/.my.cnf.j2'
    dest: '/root/.my.cnf'

- name: Create .configured file
  file:
    path: '/etc/mysql/.configured'
    state: touch

- name: Stop MySQL
  service:
    name: mysql
    state: stopped

- name: Configure 'my.cnf'
  template:
    src: 'RedHat/my.cnf.j2'
    dest: '{{ galera_mycnf_path }}'

# - name: Start Galera (Master)
#   service:
#     name: mysql
#     state: started
#     args: '--wsrep-new-cluster'
#   when: galera_role == 'master'

- name: Start Galera (Master)
  command:
    'service mysql start --wsrep-new-cluster'
  when: galera_role == 'master'

- name: Start Galera (Secondary)
  service:
    name: mysql
    state: started
