---
- name: Add MariaDB Repository
  template:
    src: 'RedHat/mariadb.repo.j2'
    dest: '/etc/yum.repos.d/mariadb.repo'

- name: Install Galera
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - mariadb-server
  - mariadb
  - MySQL-python

- include_vars: RedHat.yml
