---
- name: Install NPM
  apt:
    name: npm
    state: present

- name: Install 'n'
  shell:
    'npm install -g n'

- name: Install the latest stable version of NodeJS
  shell:
    'n stable'

- name: Get the version of NodeJS that was installed
  shell:
    'n --stable'
  register: parse_node_version

- name: Create Symlinks for NodeJS
  file:
    src: '/usr/local/n/versions/node/{{ parse_node_version.stdout }}/bin/node'
    path: '/usr/local/bin/nodejs'
    state: link

- name: Create Symlink for NPM
  file:
    src: '/usr/local/n/versions/node/{{ parse_node_version.stdout }}/bin/npm'
    path: '/usr/local/bin/npm'
    state: link

- name: Install NPM packages
  shell:
    'npm install -g {{ item }}'
  with_items: '{{ parse_npm_pkgs }}'

# - name: Create Symlink for PM2
#   file:
#     src: '/usr/local/n/versions/node/{{ parse_node_version.stdout }}/bin/pm2'
#     path: '/usr/local/bin/pm2'
#     state: link

# - name: Create Symlink for PM2
#   file:
#     src: '/usr/local/n/versions/node/{{ parse_node_version.stdout }}/bin/{{ item }}'
#     path: '/usr/local/bin/{{ item }}'
#     state: link
#   with_items:
#     - 'parse-server'
#     - 'parse-dashboard'
