---
- name: Copy /etc/default/jenkins
  template:
    src: 'Common/jenkins.j2'
    dest: '/etc/default/jenkins'

- name: Set Jenkins URL
  template:
    src: 'Common/jenkins.model.JenkinsLocationConfiguration.xml.j2'
    dest: '/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml'

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Enable Jenkins
  service:
    name: jenkins
    enabled: yes

- name: Wait for Jenkins to initialize
  wait_for:
    timeout: 30

- name: Install Jenkins Plugins
  shell:
    'java -jar {{ jenkins_cli }} -s {{ jenkins_url }} install-plugin {{ item }}'
  with_items: jenkins_plugins

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to initialize
  wait_for:
    timeout: 60
