---
- include: install_master_debian.yml
  when:
    - ansible_os_family == 'Debian'
    - jenkins_role == 'master'

- include: install_master_redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - jenkins_role == 'master'

- include: configure_master_common.yml
  when: jenkins_role == 'master'

- include: install_slave_debian.yml
  when:
    - ansible_os_family == 'Debian'
    - jenkins_role == 'slave'

- include: install_slave_redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - jenkins_role == 'slave'
